// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ZQ4b8DmHqmV0Wiry6jo3kgSQ5MZKEqk',
    appId: '1:727048337784:web:7253ae517dbcfe0d9db08d',
    messagingSenderId: '727048337784',
    projectId: 'krizot-66232',
    authDomain: 'krizot-66232.firebaseapp.com',
    storageBucket: 'krizot-66232.appspot.com',
    measurementId: 'G-BX64TCZDV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkRFVupJ8HHD-n_hcugWyG5_cnK6EWfLg',
    appId: '1:727048337784:android:3ab62a4a0527ae089db08d',
    messagingSenderId: '727048337784',
    projectId: 'krizot-66232',
    storageBucket: 'krizot-66232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDirykqN1YqIfuE1wM-Ch5DDUx3E1kKkRo',
    appId: '1:727048337784:ios:3ee9ad78861280fa9db08d',
    messagingSenderId: '727048337784',
    projectId: 'krizot-66232',
    storageBucket: 'krizot-66232.appspot.com',
    iosClientId: '727048337784-hh74j03mb7mhsmthgrdpqs1g08r1ct3m.apps.googleusercontent.com',
    iosBundleId: 'com.master1590.krizot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDirykqN1YqIfuE1wM-Ch5DDUx3E1kKkRo',
    appId: '1:727048337784:ios:3ee9ad78861280fa9db08d',
    messagingSenderId: '727048337784',
    projectId: 'krizot-66232',
    storageBucket: 'krizot-66232.appspot.com',
    iosClientId: '727048337784-hh74j03mb7mhsmthgrdpqs1g08r1ct3m.apps.googleusercontent.com',
    iosBundleId: 'com.master1590.krizot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa7BgIl3ZXWojr15fm_qQBKSYnYbDRutY',
    appId: '1:727048337784:web:67a334bc3f0cda029db08d',
    messagingSenderId: '727048337784',
    projectId: 'krizot-66232',
    authDomain: 'krizot-66232.firebaseapp.com',
    storageBucket: 'krizot-66232.appspot.com',
    measurementId: 'G-GLPW9ZBTZM',
  );
}
